name: Investment-Calculator
on: [push]
jobs:
  build:
    name: Testing Calculator
    runs-on: macos-latest
    steps:
      - name: initial setup
        uses: actions/checkout@v2
      - name: setting up java
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.2
      - name: setting up clojure
        uses: DeLaGuardo/setup-clojure@2.0
        with:
          lein: 2.9.1
      - name: running tests
        run: lein kaocha
        env:
          CI: true
